### ISSUE TITLE
Problema com alinhamento do cursor

### ISSUE THREAD

**Issue by rodigu** [andrebnf/nt-listas-excc#12]
No editor de código, o cursor acaba ficando fora de alinhamento conforme se vai escrevendo.
Cursor volta pro final e passa a acompanhar o fim da linha quando um caractere especial é usado.
![cursor_alignment_issue](https://user-images.githubusercontent.com/58960796/181652864-16e2f5dc-6b8a-43dc-a693-217f5ef6a097.gif)
Só não funciona no zoom normal:
![zoom_cursor_alignment_issue](https://user-images.githubusercontent.com/58960796/181655229-1d2c06cc-b8bf-49d0-89c2-96229204691c.gif)

**Comment by rodigu** [comment]
Parece que o espaço entre as letras ou a fonte que aparece na escrita e o usado na seleção do cursor são diferentes.
Olá mundo selecionado:
![image](https://user-images.githubusercontent.com/58960796/181653895-0ce418db-f7bf-4210-9872-54d44e6edc45.png)
Parêntesis selecionado:
![image](https://user-images.githubusercontent.com/58960796/181653968-52038ced-9d78-4d84-bdfa-903742a3c011.png)

**Comment by andrebnf** [comment]
@rodigu qual navegador utilizado?

**Comment by andrebnf** [comment]
Minha melhor hipótese até o momento é que o Monaco Editor não esteja reconhecendo a fonte que utilizamos para o código (Fire Code). Achei [esse post](https://stackoverflow.com/questions/58271107/offset-between-text-and-cursor-with-the-monaco-editor-angular-under-chrome-m) reportando o mesmo problema.

Vou testar aqui removendo a fonte customizada e tentar reproduzir

**Comment by andrebnf** [comment]
@rodigu pode testar nessa versão aqui please? https://nt.bonfatti.dev/

Esse era um domínio que eu tinha parado, estou usando como ambiente de staging (documentação inicial aqui: https://github.com/andrebnf/nt-listas-excc/issues/13)

Removi a fonte custom, só que não da pra testar no ambiente de previa, pois a url muda dinamicamente (e isso faz o login não funcionar). Pra isso criei esse novo ambiente
