### ISSUE TITLE
Feature Request: Linha de código com erro

### ISSUE THREAD

**Issue by rodigu** [andrebnf/nt-listas-excc#5]
Mostrar a linha de código que dá o erro no editor:
![image](https://user-images.githubusercontent.com/58960796/180333825-e6eb1663-2545-436c-b1c2-9f6527181dd4.png)

**Comment by andrebnf** [comment]
Feature adicionada nestes commits: 

https://github.com/andrebnf/nt-listas-excc/commit/85c69dacdb3e941b2fbba371e3dabcc20fcc0996
https://github.com/andrebnf/nt-listas-excc/commit/85c69dacdb3e941b2fbba371e3dabcc20fcc0996
