### ISSUE TITLE
Organização de Arquivos

### ISSUE THREAD

**Issue by rodigu** [andrebnf/nt-listas-excc#6]
Se colocar os exercícios dentro de um arquivo na pasta `_exercises`, o código ainda funciona?
Por exemplo:
```bash
└───_exercises
    └───m4
        └───a3
            ├───ex1.md
            └───ex2.md
```
Acho que também seria bom ter um arquivo para cada turma, já que o módulo 4 da turma 2 provavelmente não será o mesmo módulo 4 da turma 1.

**Comment by andrebnf** [comment]
Legal! Bom input @rodigu. 

Hoje somente o primeiro nível dentro de `_exercises` é lido.

Acho que podemos mudar o nome de `_exercises` para `_conteudo` para ficar algo mais genérico e adicionar os níveis: turma, módulo, aula:

```
_conteudo
├── turma1
│   └── modulo4
│       ├── aula3
│       │   ├── aula.md
│       │   ├── ex1.md
│       │   └── ex2.md
│       └── aula4
│           ├── aula.md
│           └── ex1.md
└── turma2
    └── modulo1
        └── aula1
            ├── aula.md
            └── ex1.md
```

Ainda proponho de deixarmos os níveis fixos (turma > modulo > aula > arquivos) pois se fizermos uma varredura recursiva na pasta '_conteudo' podemos abrir brechas para ficar bagunçado.
